Filtering Alerts (TR-56)
the-solo-coder/trrader pull request #12
Opened 2021-09-15 19:55 UTC by njteh7

2021-09-15 20:39 UTC, ashwin319 requested changes

2021-09-15 20:39 UTC, ashwin319 commented on client/src/Components/Alerts/AlertList.js
> +        {list.filter(alert => alert.creator == creatorId).map(alert => (
this approach works well; however, I find it more readable to move more complex logic out of the html template and into the controller.

I suggest making this line:
`{alertsByCreator.map(alert => (`

and define `alertsByCreator` above where you're fetching the creatorId

2021-09-15 20:39 UTC, ashwin319 commented on client/src/Components/Alerts/AlertList.js
> +import { PROFILE } from "../../constants/constants";
in a previous pull request, I had mentioned this `PROFILE` constant should be defined either in a constant called something like `LOCAL_STORAGE_KEYS` or in it's own constants file

2021-09-15 20:39 UTC, ashwin319 commented on client/src/Components/Alerts/AlertList.js
> +import { PROFILE } from "../../constants/constants";
can you set that as part of this pull request. It's not very clear what PROFILE is supposed to be just by reading the code

2021-09-15 20:39 UTC, ashwin319 commented on client/src/Components/Alerts/AlertList.js
> +  const creatorId = JSON.parse(localStorage.getItem(PROFILE)).result._id;
is this value `localStorage.getItem(PROFILE)` always guaranteed to exist? If not, what should we do to handle scenarios where it doesn't exist?

2021-09-15 22:14 UTC, ashwin319 commented on client/src/Components/Alerts/AlertList.js
> +import { PROFILE } from "../../constants/constants";
```
const LOCAL_STORAGE_KEYS = {
   PROFILE: 'profile'
}
```

2021-09-15 22:15 UTC, ashwin319 commented on client/src/Components/Alerts/AlertList.js
> +import { PROFILE } from "../../constants/constants";
`import { PROFILE } from "../../constants/localStorageKeys";`

2021-09-16 13:51 UTC, ashwin319 approved these changes

2021-09-16 22:00 UTC, sergiobtos approved these changes

2021-09-16 22:08 UTC, merged