Update README.md
the-solo-coder/trrader pull request #23
Opened 2021-10-24 18:24 UTC by njteh7

Go to [this branch](https://github.com/the-solo-coder/trrader/tree/TR-83_readme.md) to see how the readme.md looks like.

In the author section I included anyone that contributed in the project. If there is someone missing or extra please let me know. 
If anyone has any other suggestions to add or delete, let me know.

2021-10-25 19:41 UTC, thegrandstaff requested changes
I haven't gotten Sona's github account, but include her name.

2021-10-25 21:00 UTC, thegrandstaff approved these changes

2021-10-26 23:40 UTC, alessandra60 approved these changes
Only some suggestions:
- I think you can include Javas Script and css;

2021-10-27 02:15 UTC, alessandra60 approved these changes

2021-10-27 21:24 UTC, merged